# Generated by Django 5.2.6 on 2025-10-23 01:15

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tb_category",
            },
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do evento"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        size=None,
                        verbose_name="Tópicos",
                    ),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Logradouro")),
                (
                    "complement",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Complemento"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=100, verbose_name="Estado")),
                ("country", models.CharField(max_length=100, verbose_name="País")),
                (
                    "zip_code",
                    models.CharField(max_length=8, verbose_name="Código postal"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Data de início")),
                ("end_date", models.DateTimeField(verbose_name="Data de término")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberto"),
                            ("CLOSED", "Fechado"),
                            ("FINISHED", "Finalizado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="OPEN",
                    ),
                ),
                (
                    "participants_limit",
                    models.IntegerField(
                        null=True, verbose_name="Limite de participantes"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        max_length=500, null=True, verbose_name="URL da imagem"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="events.categorymodel",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "db_table": "tb_events",
            },
        ),
    ]
