# Generated by Django 5.2.6 on 2025-10-28 01:01

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="eventmodel",
            options={"verbose_name": "Evento", "verbose_name_plural": "Eventos"},
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nome da categoria"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.categorymodel",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="complement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="country",
            field=models.CharField(
                default="Brasil", max_length=100, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL da imagem"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="participants_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Limite de participantes"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Aberto"),
                    ("CLOSED", "Fechado"),
                    ("FINISHED", "Finalizado"),
                    ("CANCELED", "Cancelado"),
                ],
                default="OPEN",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
                verbose_name="Tópicos",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador do evento",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Código postal"),
        ),
        migrations.CreateModel(
            name="EventParticipantModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Presente"), ("ABSENT", "Ausente")],
                        max_length=20,
                        null=True,
                        verbose_name="Status da participação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants_records",
                        to="events.eventmodel",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante do Evento",
                "verbose_name_plural": "Participantes dos Eventos",
                "db_table": "tb_events_participants",
            },
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_events",
                through="events.EventParticipantModel",
                through_fields=("event", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participantes",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(
                fields=["start_date", "end_date"], name="tb_events_start_d_3c604c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(fields=["status"], name="tb_events_status_939f8e_idx"),
        ),
        migrations.AddIndex(
            model_name="eventmodel",
            index=models.Index(
                fields=["category"], name="tb_events_categor_32a032_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventparticipantmodel",
            unique_together={("user", "event")},
        ),
    ]
