# Generated by Django 5.2.6 on 2025-10-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0002_alter_categorymodel_options_alter_eventmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventparticipantmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
