# Generated by Django 5.2.6 on 2025-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_categorymodel_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipantmodel",
            name="attended_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data/hora da confirmação de presença",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipantmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Presente"),
                    ("ABSENT", "Ausente"),
                    ("PENDING", "Pendente"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status da participação",
            ),
        ),
    ]
