# Generated by Django 5.2.6 on 2025-11-10 23:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplateModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do template"),
                ),
                ("html_content", models.TextField(verbose_name="Conteúdo HTML")),
                (
                    "width",
                    models.FloatField(default=1200.0, verbose_name="Largura (px)"),
                ),
                (
                    "height",
                    models.FloatField(default=800.0, verbose_name="Altura (px)"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de certificado",
                "verbose_name_plural": "Templates de certificado",
                "db_table": "tb_certificate_template",
            },
        ),
    ]
