# Generated by Django 5.2.6 on 2025-10-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Estudante"), ("TEACHER", "Professor")],
                default="STUDENT",
                max_length=254,
            ),
        ),
    ]
