# Generated by Django 5.2.6 on 2025-10-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_usermodel_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usermodel",
            managers=[],
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
