# Generated by Django 5.2.6 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_usermodel_managers_alter_usermodel_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Estudante"),
                    ("TEACHER", "Professor"),
                    ("ADMIN", "Administrador"),
                ],
                default="STUDENT",
                max_length=254,
            ),
        ),
    ]
